### ISSUE TITLE
laravelbsdate usage issue

### ISSUE THREAD

**Issue by sarojbrt1** [shankhadevpadam/laravelbsdate#4]
sir i don't know how to use this code. i am new in laravel\

Usage
Bsdate::eng_to_nep(2016,12,31); //For converting AD TO BS
Bsdate::nep_to_eng(2073,09,16); //For converting BS TO AD
// output 
Array
(
    [year] => २०७३
    [month] => ९
    [date] => १६
    [day] => शनिबार
    [nmonth] => पुष
    [num_day] => ७
)

. i tried to convert with  Bsdate::eng_to_nep(2016,12,31);   this code but it dilplay error..

**Comment by shankhadevpadam** [comment]
Please see the output return by function. It return array. Debug the array for your desired output.

**Comment by sarojbrt1** [comment]
sir could you please share me your code that you used..

**Comment by shankhadevpadam** [comment]
```
dd(Bsdate::eng_to_nep(2016,12,31)); 
```
Check the output.

**Comment by sarojbrt1** [comment]
thanks sir problem is solved.
