### ISSUE TITLE
Class 'Bsdate' not found (0)

### ISSUE THREAD

**Issue by sarojbrt1** [shankhadevpadam/laravelbsdate#5]
### Class 'Bsdate' not found (0)

{{ ((\Bsdate::eng_to_nep(date_parse($post->created_at)["year"],date_parse($post->created_at)["month"],date_parse($post->created_at)["day"]))["day"]) }}
                  {{ ((\Bsdate::eng_to_nep(date_parse($post->created_at)["year"],date_parse($post->created_at)["month"],date_parse($post->created_at)["day"]))["num_day"]) }} {{','}}
                  {{ ((\Bsdate::eng_to_nep(date_parse($post->created_at)["year"],date_parse($post->created_at)["month"],date_parse($post->created_at)["day"]))["nmonth"]) }}
                  {{ ((\Bsdate::eng_to_nep(date_parse($post->created_at)["year"],date_parse($post->created_at)["month"],date_parse($post->created_at)["day"]))["year"]) }}

this is my code to display nepali date . it work fine in laravel 5.4 , it display error in 5.7  Class 'Bsdate' not found

**Comment by sarojbrt1** [comment]
![whoops there was an error](https://user-images.githubusercontent.com/26882827/50569934-e7692e00-0d9c-11e9-84d4-4407140b4c1e.png)

**Comment by shankhadevpadam** [comment]
i am still developing the new version of package which support in laravel 5.5 and above. Which is not complete yet.
https://github.com/shankhadevpadam/bsdate
